[project]
name = "weatherwallpaper"
version = "0.1.0"
description = "Dynamic weather desktop wallpaper for GNOME based on ECMWF IFS data and Tokyo Night aesthetic."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ecmwf-opendata",
    "xarray",
    "cfgrib",
    "eccodes",
    "matplotlib",
    "cartopy",
    "numpy",
    "scipy",
    "pandas"
]
